# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TermPaper < Formula
  desc "Typst-based coursework documentation generator and PDF builder"
  homepage "https://github.com/vasyukov1/hse-coursework-docs"
  version "0.2.0"
  license "MIT"

  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.2.0/term-paper_0.2.0_darwin_amd64.tar.gz"
      sha256 "e37b5e90001abd0eee828825db954c7bf3d8948911cac1291a2fc4788d2c39b9"

      define_method(:install) do
        bin.install "term-paper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.2.0/term-paper_0.2.0_darwin_arm64.tar.gz"
      sha256 "4f6b862e86149917531958f6e012d153d89e50c2d0c0d40bfb3c7d8aa1763a9b"

      define_method(:install) do
        bin.install "term-paper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.2.0/term-paper_0.2.0_linux_amd64.tar.gz"
      sha256 "e5507d6463f3686ecadc4e38a3b9b5a01b48e1e6309092b68fcd070e203761e1"
      define_method(:install) do
        bin.install "term-paper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.2.0/term-paper_0.2.0_linux_arm64.tar.gz"
      sha256 "8ad8a167ee2c439510ebe109566063934f7ea03dc90449a19c9a567d7d6bac4b"
      define_method(:install) do
        bin.install "term-paper"
      end
    end
  end

  test do
    system "#{bin}/term-paper", "init", "--output", testpath/"demo"
    system "#{bin}/term-paper", "generate-doc", "--output", testpath/"demo", "--doc", "pz", "--skip-ai"
    assert_path_exists testpath/"demo"/"term-paper.yaml"
    cd testpath/"demo" do
      system "#{bin}/term-paper", "doctor"
    end
  end
end
