# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TermPaper < Formula
  desc "Typst-based coursework documentation generator and PDF builder"
  homepage "https://github.com/vasyukov1/hse-coursework-docs"
  version "0.1.1"
  license "MIT"

  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.1.1/term-paper_0.1.1_darwin_amd64.tar.gz"
      sha256 "e21352ee6e81714e0f9bdd2121b63ed30779f9e322ea032dae1fab7ef41c57c0"

      define_method(:install) do
        bin.install "term-paper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.1.1/term-paper_0.1.1_darwin_arm64.tar.gz"
      sha256 "5425fb6632eb229b81281cb9ba4d8cdc070ad79bc8938764a69e61101de9e589"

      define_method(:install) do
        bin.install "term-paper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.1.1/term-paper_0.1.1_linux_amd64.tar.gz"
      sha256 "3aa5dedf4602ebeeb36ed5266dd14b260adaf452417a7aec416c216a29cd0ff5"
      define_method(:install) do
        bin.install "term-paper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vasyukov1/hse-coursework-docs/releases/download/v0.1.1/term-paper_0.1.1_linux_arm64.tar.gz"
      sha256 "df9b4d801b33e0390cdff21ca2e322f6381a5adf11ac24831dd9fa490474ad6b"
      define_method(:install) do
        bin.install "term-paper"
      end
    end
  end

  test do
    system "#{bin}/term-paper", "init", "--output", testpath/"demo"
    system "#{bin}/term-paper", "generate", "--output", testpath/"demo", "--doc", "tz", "--skip-ai"
    assert_path_exists testpath/"demo"/"term-paper.yaml"
    cd testpath/"demo" do
      system "#{bin}/term-paper", "doctor"
    end
  end
end
